[phases.setup]
nixPkgs = ['chromium', 'nss', 'glib', 'atk', 'cups', 'gtk3', 'pango', 'cairo', 'gdk-pixbuf', 'xorg.libX11', 'xorg.libXcomposite', 'xorg.libXdamage', 'xorg.libXext', 'xorg.libXfixes', 'xorg.libXrandr', 'xorg.libxcb', 'xorg.libXkbcommon', 'mesa', 'alsa-lib', 'at-spi2-core', 'dbus', 'expat', 'libdrm', 'libxkbcommon', 'nspr']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['cd client && npm install && npm run build']

[start]
cmd = 'node server.js'
